#!/bin/sh
set -e

# Generic slate entrypoint. Merges the main checkout's .env (shared secrets)
# with the workspace's .env.container (per-workspace overrides) into /app/.env.
# Safe even if both paths resolve to the same inode (writes to temp first).

if [ -f /run/main-env/.env ]; then
    TMP=$(mktemp)
    {
        printf '# GENERATED by slate on container boot. Do not edit.\n'
        printf '# Source: $MAIN_ROOT/.env + .env.container\n\n'
        cat /run/main-env/.env
        if [ -f /app/.env.container ]; then
            printf '\n# --- .env.container overrides ---\n'
            cat /app/.env.container
        fi
    } > "$TMP"
    cp "$TMP" /app/.env
    rm -f "$TMP"
fi

exec "$@"
