#!/bin/sh
set -e

# Builds /app/.env by merging the root .env (if present) with .env.container,
# for apps that read a physical .env (e.g. Laravel, where .env is gitignored
# and a fresh worktree ships none). Only a file slate generated (recognised by
# the header) is ever rewritten; a .env the worktree ships (e.g. tracked in
# git) is left untouched, since overwriting it would dirty the user's worktree.
# Overrides still reach those apps as process env via compose env_file.

HEADER='# GENERATED by slate on container boot. Do not edit.'

if [ -f /run/main-env/.env ] || [ -f /app/.env.container ]; then
    if [ ! -f /app/.env ] || [ "$(head -n 1 /app/.env)" = "$HEADER" ]; then
        TMP=$(mktemp)
        {
            printf '%s\n' "$HEADER"
            printf '# Source: $MAIN_ROOT/.env (if present) + .env.container\n\n'
            if [ -f /run/main-env/.env ]; then
                cat /run/main-env/.env
            fi
            if [ -f /app/.env.container ]; then
                printf '\n# --- .env.container overrides ---\n'
                cat /app/.env.container
            fi
        } > "$TMP"
        # Write via temp file + cmp so this is safe even when paths resolve to
        # the same inode, and no-ops when nothing changed.
        if ! cmp -s "$TMP" /app/.env; then
            cp "$TMP" /app/.env
        fi
        rm -f "$TMP"
    else
        echo "slate: /app/.env exists and is not slate-generated; leaving it untouched" >&2
    fi
fi

exec "$@"
