#!/bin/sh
set -e

# Builds /app/.env by merging the root .env (if present) with .env.container.
# The root .env is optional. When neither source exists, leave /app/.env alone
# rather than clobber what the worktree ships. Writes via a temp file so it is
# safe even when paths resolve to the same inode.

if [ -f /run/main-env/.env ] || [ -f /app/.env.container ]; then
    TMP=$(mktemp)
    {
        printf '# GENERATED by slate on container boot. Do not edit.\n'
        printf '# Source: $MAIN_ROOT/.env (if present) + .env.container\n\n'
        if [ -f /run/main-env/.env ]; then
            cat /run/main-env/.env
        fi
        if [ -f /app/.env.container ]; then
            printf '\n# --- .env.container overrides ---\n'
            cat /app/.env.container
        fi
    } > "$TMP"
    if ! cmp -s "$TMP" /app/.env; then
        cp "$TMP" /app/.env
    fi
    rm -f "$TMP"
fi

exec "$@"
